Repository teamleadercrm/api, pull requests merged in 2018-05, with the labels that each got.

#126 Add created_at and updated_at to invoices and creditnotes endpoints
  apiary.apib
  src/05-invoicing/credit-notes.apib
  src/05-invoicing/invoices.apib
Labels: TEAM - Invoicing

#142 Add proposal for the deals.lose endpoint
  apiary.apib
  src/03-deals/deals.apib
Labels: proposal

#140 Group customer and for attention of into invoicee on invoices.draft and update
  apiary.apib
  src/05-invoicing/invoices.apib
Labels: TEAM - Invoicing

#146 Add payment reference property to invoices.info
  apiary.apib
  src/05-invoicing/invoices.apib
Labels: TEAM - Invoicing

#62 Add custom field endpoints
  apiary.apib
  src/01-general/custom-fields.apib
  src/apiary.apib
Labels: proposal

#147 Add custom fields to deals.create endpoint
  apiary.apib
  src/03-deals/deals.apib
  src/datastructures.apib
Labels: enhancement

#76 Add timetracking endpoints proposal
  apiary.apib
  src/06-time-tracking/time-tracking.apib
  src/apiary.apib
Labels: proposal

#148 Add proposal for the deals.delete endpoint
  apiary.apib
  src/03-deals/deals.apib
Labels: enhancement

#150 Allow partial updates for invoices.update
  apiary.apib
  src/05-invoicing/invoices.apib
Labels: TEAM - Invoicing

#155 Add preferred_currency to companies.list and companies.info
  apiary.apib
  src/02-crm/companies.apib
Labels: TEAM - Invoicing

#156 Add payment_term to company and contact
  apiary.apib
  src/02-crm/companies.apib
  src/02-crm/contacts.apib
Labels: TEAM - Core, TEAM - Invoicing, proposal

#159 Improve text in api documentation
  apiary.apib
  src/99-other/migrating.apib
Labels: enhancement
