Repository teamleadercrm/api, pull requests merged in 2018-06, with the labels that each got.

#171 Don't allow tracking directly on a project for now
  apiary.apib
  src/06-time-tracking/time-tracking.apib
  src/06-time-tracking/timers.apib
Labels: bug

#169 Add extended_description to line item
  apiary.apib
  src/03-deals/quotations.apib
  src/05-invoicing/credit-notes.apib
  src/05-invoicing/invoices.apib
Labels: TEAM - Invoicing, proposal

#173 Marketing mails consent
  apiary.apib
  src/02-crm/companies.apib
  src/02-crm/contacts.apib
Labels: TEAM - Core

#172 CreditNote Download endpoint
  apiary.apib
  src/05-invoicing/credit-notes.apib
  src/05-invoicing/invoices.apib
Labels: TEAM - Invoicing, proposal

#174 contacts: add custom fields to write endpoints
  apiary.apib
  src/02-crm/contacts.apib
Labels: enhancement

#175 Add product category id to invoices update
  apiary.apib
  src/05-invoicing/invoices.apib
Labels: TEAM - Invoicing, proposal

#170 Document usage of markdown for remark fields
  apiary.apib
  src/02-crm/companies.apib
  src/02-crm/contacts.apib
Labels: enhancement

#176 Add documentation for extended_description fields on invoices
  apiary.apib
  src/05-invoicing/invoices.apib
Labels: TEAM - Invoicing, proposal

#178 Add amount due to invoices.list
  apiary.apib
  src/05-invoicing/invoices.apib
Labels: TEAM - Invoicing, proposal

#179 Add correct filters for invoices and credit notes list
  apiary.apib
  src/05-invoicing/credit-notes.apib
  src/05-invoicing/invoices.apib
Labels: proposal

#182 Timetracking.add variant with ended_at
  apiary.apib
  src/06-time-tracking/time-tracking.apib
Labels: enhancement

#181 Add documentation for timers.update endpoint
  apiary.apib
  src/06-time-tracking/timers.apib
Labels: enhancement
