Repository teamleadercrm/api, pull requests merged in 2018-07, with the labels that each got.

#34 webhooks.register
  apiary.apib
  src/99-other/webhooks.apib
  src/apiary.apib
Labels: hold

#184 Linter doesn't yet support node 10
  Makefile
Labels: bug

#191 Add filter on updated_since for deals.list
  apiary.apib
  src/03-deals/deals.apib
Labels: enhancement

#194 webhooks.list
  apiary.apib
  src/99-other/webhooks.apib
Labels: enhancement
