Repository teamleadercrm/api, pull requests merged in 2018-10, with the labels that each got.

#226 Fix typo
  CONTRIBUTING.md
Labels: enhancement

#227 Fix some typo's and improve some language constructs
  apiary.apib
  src/authentication.apib
  src/introduction.apib
Labels: enhancement

#228 Add account.deactivated webhook
  apiary.apib
  src/datastructures.apib
Labels: proposal

#229 Add an account.deleted webhook
  apiary.apib
  src/datastructures.apib
Labels: enhancement

#230 Add an user.deactivated webhook
  apiary.apib
  src/datastructures.apib
Labels: enhancement, hold

#233 [CORE-1380] document company_id filter on contacts list endpoint
  apiary.apib
  src/02-crm/contacts.apib
Labels: TEAM - Core
