Repository teamleadercrm/api, pull requests merged in 2018-11, with the labels that each got.

#234 Line item discounts are now optional when updating an invoice
  apiary.apib
  src/05-invoicing/invoices.apib
Labels: TEAM - Invoicing

#110 More information about departments
  apiary.apib
  src/01-general/departments.apib
Labels: TEAM - Core, proposal

#250 Fix internal anchor links
  apiary.apib
  src/changes.apib
Labels: enhancement

#248 Add electronic invoicing address to customer modules
  apiary.apib
  src/02-crm/companies.apib
  src/02-crm/contacts.apib
Labels: TEAM - Core, TEAM - Invoicing, proposal

#238 Add fiscal_regime to department info
  apiary.apib
  src/01-general/departments.apib
Labels: TEAM - Invoicing, hold

#253 IN-984 Add withholding tax rates list
  apiary.apib
  src/05-invoicing/withholding-tax-rates.apib
  src/apiary.apib
Labels: TEAM - Invoicing
