Repository teamleadercrm/api, pull requests merged in 2018-08, with the labels that each got.

#196 webhooks.unregister
  apiary.apib
  src/99-other/webhooks.apib
  src/datastructures.apib
Labels: enhancement

#199 Add invoicee email and local_business_number to invoices info
  apiary.apib
  src/05-invoicing/invoices.apib
Labels: TEAM - Invoicing

#198 [CORE-1048] Update default sorting for contacts.list
  apiary.apib
  src/02-crm/contacts.apib
Labels: refactor

#197 Added the totals to the api template that are needed for the invoice detail page.
  apiary.apib
  src/03-deals/quotations.apib
  src/05-invoicing/credit-notes.apib
  src/05-invoicing/invoices.apib
Labels: TEAM - Invoicing, help wanted, hold, proposal

#200 Add invoicee email and local_business_number to credit note info
  apiary.apib
  src/05-invoicing/credit-notes.apib
Labels: TEAM - Invoicing

#202 [CORE-1049] Contacts.list sort on date_updated
  apiary.apib
  src/02-crm/contacts.apib
Labels: enhancement

#204 Contacts.list: add sorting on added_at
  apiary.apib
  src/02-crm/contacts.apib
Labels: enhancement

#205 Update missing documentation for timeTracking.delete
  apiary.apib
  src/06-time-tracking/time-tracking.apib
Labels: enhancement

#207 Include the new sorting on companies.list
  apiary.apib
  src/02-crm/companies.apib
Labels: enhancement

#209 Fix `tax_rate_id` field name in invoices.update endpoint
  src/05-invoicing/invoices.apib
Labels: TEAM - Invoicing, bug
