Repository teamleadercrm/api, pull requests merged in 2018-02, with the labels that each got.

#66 [CAL-300] Add links to event.list
  apiary.apib
  src/03-calendar/events.apib
Labels: TEAM - Calendar

#70 [CORE-449] Companies.add: tags
  apiary.apib
  src/02-crm/companies.apib
Labels: hold

#27 Proposal for taxRates.list ordering and paging
  apiary.apib
  src/04-invoicing/tax-rates.apib
Labels: proposal
