Repository teamleadercrm/api, pull requests merged in 2019-09, with the labels that each got.

#466 [IN-2034] Added a filter for created before to deals list
  apiary.apib
  src/03-deals/deals.apib
  src/changes-backwards-compatible.apib
Labels: TEAM - Invoicing, enhancement

#468 [IN-2050] estimated closing date filter
  apiary.apib
  src/03-deals/deals.apib
  src/changes-backwards-compatible.apib
Labels: TEAM - Invoicing

#471 Billing method and budget in milestones.create [PRO-2436]
  apiary.apib
  src/07-projects/milestones.apib
  src/changes-backwards-incompatible.apib
Labels: Team Bowie :zap:

#472 completed_at is nullable on tasks.info
  apiary.apib
  src/08-tasks/tasks.apib
Labels: Team Marc :de:, bug
