Repository teamleadercrm/api, pull requests merged in 2019-10, with the labels that each got.

#475 IN-2161 Add status filter to deals list
  apiary.apib
  src/03-deals/deals.apib
Labels: TEAM - Invoicing

#478 Modify deals list filter responsible_user_id to accept an array of uuids
  apiary.apib
  src/03-deals/deals.apib
  src/changes-backwards-compatible.apib
Labels: Team Pieter :monkey:

#476 🐛Fix milestone status
  apiary.apib
  src/07-projects/milestones.apib
Labels: Team Bowie :zap:, bug

#479 [PRO-2756] Custom fields on tasks
  apiary.apib
  src/08-tasks/tasks.apib
  src/changes-backwards-compatible.apib
Labels: Team Bowie :zap:, hold until deploy

#480 milestones.delete [PRO-2747]
  apiary.apib
  src/07-projects/milestones.apib
  src/changes-backwards-compatible.apib
Labels: Team Bowie :zap:
