Repository teamleadercrm/api, pull requests merged in 2019-02, with the labels that each got.

#277 Fix typo in authentication flow
  apiary.apib
  src/authentication.apib
Labels: enhancement

#283 add products.add endpoint
  apiary.apib
  src/06-products/products.apib
Labels: TEAM - Invoicing, proposal

#284 Revert "add products.add endpoint"
  apiary.apib
  src/06-products/products.apib
Labels: bug

#286 Return the invoiceability of a running timer
  apiary.apib
  src/06-time-tracking/timers.apib
Labels: enhancement

#281 Return whether or not a timetracking is invoiceable
  apiary.apib
  src/06-time-tracking/time-tracking.apib
Labels: enhancement

#289 Return the invoiceable user preference
  apiary.apib
  src/01-general/users.apib
Labels: TEAM - Core, proposal

#288 Add levelTwoAreas.list endpoint
  apiary.apib
  src/02-crm/addresses.apib
  src/apiary.apib
Labels: proposal

#282 Contacts National Identification Number
  apiary.apib
  src/02-crm/contacts.apib
Labels: TEAM - Core, enhancement

#276 Add documentation for tasks
  src/08-tasks/tasks.apib
Labels: TEAM - Calendar, hold

#292 CAL-1082 Tasks.delete
  apiary.apib
  src/08-tasks/tasks.apib
Labels: TEAM - Calendar

#270 Add custom_fields to invoices.info call
  apiary.apib
  src/05-invoicing/invoices.apib
Labels: TEAM - Invoicing, proposal

#271 Add custom_fields to invoices.draft
  apiary.apib
  src/05-invoicing/invoices.apib
Labels: TEAM - Invoicing, proposal

#301 Add estimated_duration and work_type to tasks.info and tasks.list.
  src/08-tasks/tasks.apib
Labels: TEAM - Calendar

#287 PRO-1380 Add billing method info to milestones.list
  apiary.apib
  src/07-projects/milestones.apib
Labels: TEAM - Projects, hold

#306 Use an object for estimated_duration in tasks.update
  src/08-tasks/tasks.apib
Labels: TEAM - Calendar

#296 workOrders.draft endpoint: MVP
  apiary.apib
  src/01-general/work-orders.apib
  src/apiary.apib
Labels: proposal

#304 workOrders.draft MVP: add department
  apiary.apib
  src/01-general/work-orders.apib
Labels: enhancement

#309 estimated_duration of Tasks must be in minutes
  src/08-tasks/tasks.apib
Labels: TEAM - Calendar

#303 Document the filter on term option in deals.list
  apiary.apib
  src/03-deals/deals.apib
Labels: TEAM - Core, enhancement

#257 [PRO-1251] Documentation for the project items list endpoint
  src/07-projects/project-items.apib
Labels: TEAM - Bouwie

#298 Invoiceability on timers and timetracking
  apiary.apib
  src/06-time-tracking/time-tracking.apib
  src/06-time-tracking/timers.apib
Labels: enhancement

#264 [PRO-1313] Documentation for the projectItems.info route
  src/07-projects/project-items.apib
Labels: Team Bowie :zap:

#273 Add documentation for sideloading
  apiary.apib
  src/apiary.apib
  src/sideloading.apib
Labels: hold

#312 Add quotation type to migrate.id
  apiary.apib
  src/99-other/migrating.apib
Labels: TEAM - Invoicing

#317 Add BC break for products.list endpoint
  apiary.apib
  src/06-products/products.apib
  src/changes.apib
Labels: breaking-change

#302 Add custom_fields to invoices.update
  apiary.apib
  src/05-invoicing/invoices.apib
Labels: TEAM - Invoicing

#308 Add materials to the workOrders.draft endpoint
  apiary.apib
  src/01-general/work-orders.apib
Labels: enhancement
