Repository teamleadercrm/api, pull requests merged in 2019-06, with the labels that each got.

#427 Fix paragraphs for changes regarding invoiceability of time trackings
  apiary.apib
  src/changes-backwards-compatible.apib
Labels: bug

#423 work order materials: add purchase price
  apiary.apib
  src/09-workorders/work-orders.apib
Labels: proposal

#404 Proposal for deals.report
  apiary.apib
  src/03-deals/deals.apib
Labels: proposal

#429 [CAL-1391] Return deal and milestone from list and info
  apiary.apib
  src/08-tasks/tasks.apib
  src/changes-backwards-compatible.apib
Labels: Team Marc :de:

#397 [CAL-1391] Add milestone_id and deal_id to /tasks.create and /tasks.update
  apiary.apib
  src/08-tasks/tasks.apib
  src/changes-backwards-compatible.apib
Labels: Team Marc :de:

#422 [CAL-1443] Link Customer to a task
  apiary.apib
  src/08-tasks/tasks.apib
  src/changes-backwards-compatible.apib
Labels: Team Marc :de:

#430 Fix rendering issue with estimated_duration
  apiary.apib
  src/08-tasks/tasks.apib
Labels: Team Marc :de:, bug

#425 Work hours: allow multiple assignees
  apiary.apib
  src/09-workorders/work-orders.apib
  src/changes-backwards-incompatible.apib
Labels: enhancement, proposal

#431 Remove due_at in favour of due_on for Tasks
  apiary.apib
  src/08-tasks/tasks.apib
  src/changes-backwards-incompatible.apib
Labels: Team Marc :de:, breaking-change

#435 [Cal-1492] Add task_id filter to events.list
  apiary.apib
  src/04-calendar/events.apib
  src/changes-backwards-compatible.apib
Labels: Team Marc :de:

#436 Can order tasks by due date desc
  apiary.apib
  src/08-tasks/tasks.apib
Labels: Team Marc :de:

#437 [CAL-1499] Rename todo to task
  apiary.apib
  src/04-calendar/events.apib
  src/changes-backwards-incompatible.apib
Labels: Team Marc :de:

#434 [CAL-1492] Add schedule task endpoint
  apiary.apib
  src/08-tasks/tasks.apib
  src/changes-backwards-compatible.apib
Labels: Team Marc :de:

#441 Remove non-existing invoicing email address for contacts
  apiary.apib
  src/02-crm/contacts.apib
Labels: bug

#440 Add time to the workOrders.list endpoint
  apiary.apib
  src/09-workorders/work-orders.apib
Labels: enhancement

#428 [CAL-1477] Added due_by and due_from filters to tasks.list
  apiary.apib
  src/08-tasks/tasks.apib
  src/changes-backwards-compatible.apib
Labels: Team Marc :de:

#442 [CAL-1546][CAL-1547] tasks.complete and tasks.reopen
  apiary.apib
  src/08-tasks/tasks.apib
  src/changes-backwards-compatible.apib
Labels: Team Marc :de:, hold until deploy
