Repository teamleadercrm/api, pull requests merged in 2019-08, with the labels that each got.

#455 Add products.list filter for updated_since
  apiary.apib
  src/06-products/products.apib
  src/changes-backwards-compatible.apib
Labels: TEAM - Invoicing

#459 task.list - filter on customer
  apiary.apib
  src/08-tasks/tasks.apib
Labels: TEAM - Charlotte 💪, enhancement

#460 Task.list - filter on milestone
  apiary.apib
  src/08-tasks/tasks.apib
Labels: TEAM - Charlotte 💪, enhancement

#249 Add the expected payment method to Invoices .draft, .update and .info
  apiary.apib
  src/05-invoicing/invoices.apib
  src/datastructures.apib
Labels: TEAM - Invoicing

#463 tasks.list: filter on milestone
  apiary.apib
  src/08-tasks/tasks.apib
Labels: TEAM - Charlotte 💪

#380 /userInvites.resend
  apiary.apib
  src/01-general/user-invites.apib
  src/changes-backwards-compatible.apib
Labels: TEAM IT, proposal
