Repository teamleadercrm/api, pull requests merged in 2019-04, with the labels that each got.

#335 Purchase order number for invoicing end points
  apiary.apib
  src/05-invoicing/invoices.apib
Labels: TEAM - Invoicing

#285 Add products.add endpoint
  apiary.apib
  src/06-products/products.apib
Labels: TEAM - Invoicing

#338 IN-1132 Purchase order number filter suggestion
  apiary.apib
  src/05-invoicing/invoices.apib
Labels: TEAM - Invoicing, proposal

#342 [PRO-1717] New API filter for project items: internal_cost_per_unit
  src/07-projects/project-items.apib
Labels: Team Bowie :zap:

#344 [PRO-1726] API documentation for adding a product reference to project items
  src/07-projects/project-items.apib
Labels: Team Bowie :zap:

#330 [CORE-1778] Update draft workorder
  apiary.apib
  src/09-workorders/work-orders.apib
Labels: TEAM - Core, enhancement

#340 Add payment_reference filter to the invoices.list and to the response
  apiary.apib
  src/05-invoicing/invoices.apib
Labels: TEAM - Invoicing

#345 Add the WorkOrders.finalize documentation
  apiary.apib
  src/09-workorders/work-orders.apib
Labels: enhancement

#260 [PRO-1285] Documentation for the update project item cost endpoint
  src/07-projects/project-items.apib
Labels: Team Bowie :zap:

#352 [PRO-1751] API documentation for filtering by employee id
  src/07-projects/project-items.apib
Labels: Team Bowie :zap:

#349 PRO-1746: document for projectItems.updateInternalRate
  src/07-projects/project-items.apib
Labels: Team Bowie :zap:

#362 document milestones.info invoicing_method
  apiary.apib
  src/07-projects/milestones.apib
Labels: Team Bowie :zap:

#356 add documentation for new endpoint projectItems.updateInternalHourlyCost
  src/07-projects/project-items.apib
Labels: Team Bowie :zap:, hold until release

#353 workOrders.info - add images
  apiary.apib
  src/09-workorders/work-orders.apib
Labels: enhancement

#364 [CORE-2088] WorkOrders Draft | Add Distance
  apiary.apib
  src/09-workorders/work-orders.apib
Labels: TEAM - Core, enhancement

#366 Follow-up | WorkOrders Info - Nullable fields
  apiary.apib
  src/09-workorders/work-orders.apib
Labels: enhancement

#347 [CORE-1999] WorkOrder Update Time
  apiary.apib
  src/09-workorders/work-orders.apib
Labels: TEAM - Core, enhancement

#371 Add selling_price to products.info response
  apiary.apib
  src/06-products/products.apib
Labels: TEAM - Invoicing

#358 Add documentation for a workOrders.attachImage endpoint
  apiary.apib
  src/09-workorders/work-orders.apib
Labels: proposal

#370 Allow signing WorkOrders during finalization
  apiary.apib
  src/09-workorders/work-orders.apib
Labels: proposal

#365 Add proposal for the workOrders.deleteImage endpoint
  apiary.apib
  src/09-workorders/work-orders.apib
Labels: proposal

#373 Add the documentation for the workOrders.download endpoint
  apiary.apib
  src/09-workorders/work-orders.apib
Labels: TEAM - Core, enhancement

#367 Add a filter status on users.list
  apiary.apib
  src/01-general/users.apib
Labels: enhancement

#374 Don't allow updating the meeting of a draft work order
  apiary.apib
  src/09-workorders/work-orders.apib
Labels: enhancement

#376 [CORE-1879] WorkOrders Update add Distance | Docs
  apiary.apib
  src/09-workorders/work-orders.apib
Labels: TEAM - Core
