Repository teamleadercrm/api, pull requests merged in 2019-05, with the labels that each got.

#381 PRO-1816: Add work_type, activity_type to projectItems.list endpoint filter and result
  src/07-projects/project-items.apib
Labels: Team Bowie :zap:

#377 WorkOrders List | Documentation
  apiary.apib
  src/09-workorders/work-orders.apib
Labels: TEAM - Core

#378 [TOOL-174] Add `status` to `/users.info`
  apiary.apib
  src/01-general/users.apib
  src/changes-backwards-compatible.apib
Labels: TEAM IT

#385 Fix array of strings
  apiary.apib
  src/01-general/users.apib
  src/05-invoicing/invoices.apib
Labels: question

#383 projectItem workType, activityType should be camelCased for sideloading
  src/07-projects/project-items.apib
Labels: Team Bowie :zap:

#382 WorkOrders List | Add Filter
  apiary.apib
  src/09-workorders/work-orders.apib
Labels: enhancement

#384 PRO-1839: ProjectItems.info: document subject (also work_type, activity_type)
  src/07-projects/project-items.apib
Labels: Team Bowie :zap:

#387 Follow up | Nullable Customer
  apiary.apib
  src/09-workorders/work-orders.apib
Labels: TEAM - Core, question

#386 PRO 1800: require filter.projectId attribute in projectItems.list endpoint
  src/07-projects/project-items.apib
Labels: Team Bowie :zap:

#389 Allow to filter work orders on starts_at
  apiary.apib
  src/09-workorders/work-orders.apib
Labels: enhancement

#388 WorkOrders Delete
  apiary.apib
  src/09-workorders/work-orders.apib
Labels: TEAM - Core, enhancement

#379 Add currency_exchange_rate to quotations.info
  apiary.apib
  src/03-deals/quotations.apib
  src/changes-backwards-compatible.apib
Labels: TEAM - Invoicing

#394 Add optional ids filter on invoices.list
  apiary.apib
  src/05-invoicing/invoices.apib
  src/changes-backwards-compatible.apib
Labels: TEAM - Invoicing

#396 Add sent status to invoices list and info
  apiary.apib
  src/05-invoicing/invoices.apib
  src/changes-backwards-compatible.apib
Labels: TEAM - Invoicing

#392 timeTracking.list returns results in descending order
  src/08-time-tracking/time-tracking.apib
Labels: Team Marc :de:, bug

#390 Add invoices.credit endpoint
  apiary.apib
  src/05-invoicing/invoices.apib
  src/changes-backwards-compatible.apib
Labels: TEAM - Invoicing

#391 PRO 1866 events.list: add filter by ids
  apiary.apib
  src/04-calendar/events.apib
  src/changes-backwards-compatible.apib
Labels: Team Bowie :zap:

#395 PRO 1866: tasks.list - add filtering by ids
  apiary.apib
  src/08-tasks/tasks.apib
  src/changes-backwards-compatible.apib
Labels: Team Bowie :zap:

#393 IN-993 Document webhooks creditNote.booked and product.added
  apiary.apib
  src/changes-backwards-compatible.apib
  src/datastructures.apib
Labels: TEAM - Invoicing

#398 Add ability to have WorkOrder materials without product ID
  apiary.apib
  src/09-workorders/work-orders.apib
Labels: TEAM - Core, enhancement

#399 Add custom fields to the work orders endpoints
  apiary.apib
  src/01-general/custom-fields.apib
  src/09-workorders/work-orders.apib
Labels: enhancement, hold, hold until release

#410 workOrders.list: filter on term
  apiary.apib
  src/09-workorders/work-orders.apib
Labels: proposal

#411 Allow to update the start moment of a the currently running timer
  apiary.apib
  src/08-time-tracking/timers.apib
Labels: proposal

#408 workOrders endpoints - include document_template_id
  apiary.apib
  src/09-workorders/work-orders.apib
Labels: enhancement

#416 Section should have been optional in invoices.update
  apiary.apib
  src/05-invoicing/invoices.apib
Labels: TEAM - Invoicing, bug

#418 Return name of layout in the templates.list endpoint
  apiary.apib
  src/01-general/document-templates.apib
Labels: proposal

#415 Work Orders List | Filter on Customer
  apiary.apib
  src/09-workorders/work-orders.apib
Labels: TEAM - Charlotte 💪, enhancement

#417 Allow passing a mail template id when sending a work order
  apiary.apib
  src/09-workorders/work-orders.apib
Labels: hold until release, proposal
