Repository teamleadercrm/api, pull requests merged in 2019-03, with the labels that each got.

#314 [CORE-1816] Workorder draft location
  apiary.apib
  src/08-time-tracking/time-tracking.apib
  src/08-time-tracking/timers.apib
  src/09-workorders/work-orders.apib
  src/apiary.apib
Labels: enhancement

#266 Replace `rate` with `id` and `type` in `tax` object on `invoice.info`, `creditNote.info` and `quotations.info` responses
  apiary.apib
  src/03-deals/quotations.apib
  src/05-invoicing/credit-notes.apib
  src/05-invoicing/invoices.apib
  src/changes.apib
Labels: TEAM - Invoicing

#235 Add discounts to Invoices.update endpoint
  apiary.apib
  src/05-invoicing/invoices.apib
Labels: TEAM - Invoicing

#310 Adapt API docs for new assignee format
  src/08-tasks/tasks.apib
Labels: Team Calendar

#320 Add exchange rates to invoices info
  apiary.apib
  src/05-invoicing/invoices.apib
Labels: TEAM - Invoicing, proposal

#323 Filter the project items on milestone id
  src/07-projects/project-items.apib
Labels: Team Bowie :zap:

#322 Add exchange rate to quotations.info
  apiary.apib
  src/05-invoicing/credit-notes.apib
Labels: TEAM - Invoicing

#324 Publish Tasks API docs
  apiary.apib
  src/08-tasks/tasks.apib
  src/apiary.apib
Labels: Team Calendar

#326 Add optional purchase_price to products.add endpoint
  apiary.apib
  src/06-products/products.apib
Labels: TEAM - Invoicing

#327 Add selling_price to products.add
  apiary.apib
  src/06-products/products.apib
Labels: TEAM - Invoicing

#329 Add workOrders.info endpoint
  apiary.apib
  src/09-workorders/work-orders.apib
Labels: TEAM - Core, enhancement

#325 documentTemplates.list - documentation
  apiary.apib
  src/01-general/document-templates.apib
  src/apiary.apib
Labels: TEAM - Core, enhancement

#318 Allow passing time when drafting a work order
  apiary.apib
  src/09-workorders/work-orders.apib
Labels: TEAM - Core, enhancement

#334 ProjectItems.list: add 'time_tracking_product as a type filter option
  src/07-projects/project-items.apib
Labels: Team Bowie :zap:

#332 Document products info changes
  apiary.apib
  src/06-products/products.apib
  src/changes.apib
Labels: TEAM - Invoicing, breaking-change

#295 Prepare 2019-03-13
  apiary.apib
  src/03-deals/quotations.apib
  src/05-invoicing/credit-notes.apib
  src/05-invoicing/invoices.apib
  src/06-products/products.apib
  src/changes.apib
Labels: breaking-change, hold

#333 Add guidelines to deal with user permissions for specific properties in objects
  GUIDELINES.md
Labels: proposal
