Repository teamleadercrm/api, pull requests merged in 2019-07, with the labels that each got.

#448 Fix rendering issue with enums
  apiary.apib
  src/01-general/custom-fields.apib
  src/01-general/departments.apib
  src/01-general/users.apib
  src/02-crm/companies.apib
  src/02-crm/contacts.apib
  src/02-crm/tags.apib
  src/03-deals/deals.apib
  src/03-deals/quotations.apib
  src/04-calendar/events.apib
  src/05-invoicing/credit-notes.apib
  src/05-invoicing/invoices.apib
  src/07-projects/milestones.apib
  src/07-projects/project-items.apib
  src/07-projects/projects.apib
  src/08-tasks/tasks.apib
  src/08-time-tracking/time-tracking.apib
  src/08-time-tracking/timers.apib
  src/09-workorders/work-orders.apib
  src/99-other/migrating.apib
  src/datastructures.apib
Labels: Team Marc :de:, bug

#407 Approved changes in the 2019-07-03 feature branch
  apiary.apib
  src/04-calendar/events.apib
  src/08-tasks/tasks.apib
  src/changes-backwards-compatible.apib
  src/changes-backwards-incompatible.apib
Labels: hold until release

#445 Filter milestones.list on term
  apiary.apib
  src/07-projects/milestones.apib
  src/changes-backwards-compatible.apib
Labels: Team Bowie :zap:, enhancement

#450 Add term filter to tasks.list
  apiary.apib
  src/08-tasks/tasks.apib
  src/changes-backwards-compatible.apib
Labels: Team Marc :de:

#438 [CORE-2507] Add work order webhook types
  apiary.apib
  src/datastructures.apib
Labels: enhancement, hold

#449 Allow filtering timeTracking by subject
  apiary.apib
  src/08-time-tracking/time-tracking.apib
  src/changes-backwards-compatible.apib
Labels: Team Marc :de:, hold until deploy

#456 Added project to tasks.info and tasks.list
  apiary.apib
  src/08-tasks/tasks.apib
  src/changes-backwards-compatible.apib
Labels: TEAM - Charlotte 💪, Team Bowie :zap:

#458 Add time_tracked to projects.info [PRO-2197]
  apiary.apib
  src/07-projects/projects.apib
  src/changes-backwards-compatible.apib
Labels: Team Bowie :zap:
