Repository teamleadercrm/api, pull requests merged in 2020-03, with the labels that each got.

#502 Filter tracked time on subject type [PRO-3411]
  apiary.apib
  src/08-time-tracking/time-tracking.apib
Labels: Team Wombat :koala:, proposal

#500 In-2527 summary deal info list create update
  apiary.apib
  src/03-deals/deals.apib
  src/changes-backwards-compatible.apib
Labels: Team Pieter :monkey:

#505 Work Orders | Un-publish endpoint
  apiary.apib
  src/09-workorders/work-orders.apib
  src/apiary.apib
Labels: Team Fraf

#506 IN-1678 Add webhook type deal updated
  apiary.apib
  src/datastructures.apib
Labels: Team Pieter :monkey:

#508 Allow filtering on related project [PRO-3474]
  apiary.apib
  src/08-time-tracking/time-tracking.apib
Labels: Team Wombat :koala:

#503 Added Duration datastructure
  apiary.apib
  src/datastructures.apib
Labels: Team Wombat :koala:, proposal

#510 Provide npm lock file to fix package versions
  .gitignore
  package-lock.json
Labels: Team Pieter :monkey:, bug

#509 [In-2643] Add url to the detail page to invoices list end point
  apiary.apib
  src/05-invoicing/invoices.apib
Labels: Team Pieter :monkey:

#511 Add ids filter to lostReasons.list
  apiary.apib
  src/03-deals/deals.apib
  src/changes-backwards-compatible.apib
Labels: Team Pieter :monkey:

#512 PRO-3562: document new milestones depends_on property
  apiary.apib
  src/07-projects/milestones.apib
  src/changes-backwards-compatible.apib
Labels: Team Wombat :koala:

#513 PRO-3582: document `dependency_for` in milestones.info and .list
  apiary.apib
  src/07-projects/milestones.apib
  src/changes-backwards-compatible.apib
Labels: Team Wombat :koala:

#514 PRO-3590: Document `depends_on` in milestones.create and milestones.update
  apiary.apib
  src/07-projects/milestones.apib
  src/changes-backwards-compatible.apib
Labels: Team Wombat :koala:
