Repository teamleadercrm/api, pull requests merged in 2020-01, with the labels that each got.

#483 IN-2383 Add filters estimated_closing_date range to deals.list
  apiary.apib
  src/03-deals/deals.apib
  src/changes-backwards-compatible.apib
Labels: Team Pieter :monkey:

#484 Include related workOrder in event.info
  apiary.apib
  src/04-calendar/events.apib
Labels: proposal

#485 [In-2411] Proposal for adding the option to sort based on weighted amount
  apiary.apib
  src/03-deals/deals.apib
  src/changes-backwards-compatible.apib
Labels: Team Pieter :monkey:

#487 [In-2437] added weighted value to both the list and info responses
  apiary.apib
  src/03-deals/deals.apib
  src/changes-backwards-compatible.apib
Labels: Team Pieter :monkey:

#489 Document `lead` as optional property on `deals.update`
  apiary.apib
  src/03-deals/deals.apib
Labels: Team Pieter :monkey:, bug

#488 [PRO-3017] Filtering on unassigned tasks
  apiary.apib
  src/08-tasks/tasks.apib
Labels: Team Wombat :koala:

#490 PRO-3171: provide 'extra_option_allowed' in customFieldDefinitions
  apiary.apib
  src/01-general/custom-fields.apib
  src/changes-backwards-compatible.apib
Labels: Team Wombat :koala:

#486 IN-901 Add ubl/e-fff format to invoices download
  apiary.apib
  src/05-invoicing/invoices.apib
  src/changes-backwards-compatible.apib
Labels: Team Pieter :monkey:
