Repository teamleadercrm/api, pull requests merged in 2020-05, with the labels that each got.

#523 Propagate date changes in milestones.update
  apiary.apib
  src/07-projects/milestones.apib
  src/changes-backwards-compatible.apib
Labels: Team Wombat :koala:

#524 PRO-3764: milestones.update propagate_date_changes applies recursively
  apiary.apib
  src/changes-backwards-compatible.apib
Labels: Team Wombat :koala:

#525 Add vat number to contacts.info
  apiary.apib
  src/02-crm/contacts.apib
  src/changes-backwards-compatible.apib
Labels: Team Pieter :monkey:

#481 [PRO-2764] Custom fields on task groups (milestones)
  apiary.apib
  src/07-projects/milestones.apib
  src/changes-backwards-compatible.apib
Labels: Team Wombat :koala:

#528 Custom fields on projects
  apiary.apib
  src/07-projects/projects.apib
  src/changes-backwards-compatible.apib
Labels: Team Wombat :koala:, enhancement

#526 PRO-3623 - Add purchase_order_number to projects
  apiary.apib
  src/07-projects/projects.apib
  src/changes-backwards-compatible.apib
Labels: Team Wombat :koala:

#529 Remove unused argument for timers.stop
  apiary.apib
  src/08-time-tracking/timers.apib
Labels: Team Fraf, bug
