Repository teamleadercrm/api, pull requests merged in 2020-10, with the labels that each got.

#566 [INS-217] Add file to invoices.list/info
  apiary.apib
  src/05-invoicing/invoices.apib
  src/changes-backwards-compatible.apib
Labels: Team Marc :de:

#567 Add ordering on due date or start date to milestones list [PRO-4623]
  apiary.apib
  src/07-projects/milestones.apib
  src/changes-backwards-compatible.apib
Labels: Team Wombat :koala:

#568 invoices.list/info: .invoicee.for_attention_of.name & ...contact are nullable
  apiary.apib
  src/05-invoicing/invoices.apib
Labels: Team Marc :de:, bug

#569 Customer on projects.update [PRO-4644]
  apiary.apib
  src/07-projects/projects.apib
  src/changes-backwards-compatible.apib
Labels: Team Wombat :koala:

#570 Budget on projects.update [PRO-4646]
  apiary.apib
  src/07-projects/projects.apib
  src/changes-backwards-compatible.apib
Labels: Team Wombat :koala:

#571 invoices.info .note is nullable + clarify that it is plaintext
  apiary.apib
  src/05-invoicing/invoices.apib
Labels: Team Marc :de:

#572 Milestone starts_on [PRO-4565]
  apiary.apib
  src/07-projects/milestones.apib
  src/07-projects/projects.apib
  src/changes-backwards-compatible.apib
Labels: Team Wombat :koala:

#573 Add area_level_two for customers and departments
  apiary.apib
  src/01-general/departments.apib
  src/02-crm/companies.apib
  src/02-crm/contacts.apib
  src/datastructures.apib
Labels: Team Fraf

#576 IN-2704 Mark quotation as accepted
  apiary.apib
  src/03-deals/quotations.apib
  src/changes-backwards-compatible.apib
Labels: Team Pieter :monkey:

#578 Sort projects list on title [PRO-4756]
  apiary.apib
  src/07-projects/projects.apib
  src/changes-backwards-compatible.apib
Labels: Team Wombat :koala:
