Repository teamleadercrm/api, pull requests merged in 2020-08, with the labels that each got.

#549 [IN-3055] document product_id
  apiary.apib
  src/03-deals/quotations.apib
  src/05-invoicing/invoices.apib
  src/changes-backwards-compatible.apib
Labels: Team Pieter :monkey:

#551 Remove inaccurate message again for invoices
  apiary.apib
  src/05-invoicing/invoices.apib
Labels: Team Pieter :monkey:

#553 Fix format for invoice discounts
  apiary.apib
  src/05-invoicing/invoices.apib
Labels: Team Pieter :monkey:

#498 Lock time tracking entries
  apiary.apib
  src/08-time-tracking/time-tracking.apib
  src/changes-backwards-compatible.apib
Labels: Team Wombat :koala:, hold until release, proposal

#497 Expose the freeze time tracking preference on users.me
  apiary.apib
  src/01-general/users.apib
  src/changes-backwards-compatible.apib
Labels: Team Wombat :koala:
