Repository teamleadercrm/api, pull requests merged in 2020-09, with the labels that each got.

#558 [IN-3086] document total purchase price for quotations
  apiary.apib
  src/03-deals/quotations.apib
  src/changes-backwards-compatible.apib
Labels: Team Pieter :monkey:

#559 Document projects.reopen endpoint
  apiary.apib
  src/07-projects/milestones.apib
  src/07-projects/project-items.apib
  src/07-projects/projects.apib
  src/changes-backwards-compatible.apib
Labels: Team Wombat :koala:

#560 [IN-2423] document commercial discounts
  apiary.apib
  src/03-deals/quotations.apib
  src/changes-backwards-compatible.apib
Labels: Team Pieter :monkey:

#561 [IN-3087] document quotation dates
  apiary.apib
  src/03-deals/quotations.apib
  src/changes-backwards-compatible.apib
Labels: Team Pieter :monkey:

#563 milestones.close and milestones.open
  apiary.apib
  src/07-projects/milestones.apib
  src/changes-backwards-compatible.apib
Labels: Team Wombat :koala:

#564 Include purchase_price on quotation items
  apiary.apib
  src/03-deals/quotations.apib
Labels: Team Marc :de:

#562 [INS-109] Add purchase_price to quotations.create/update
  apiary.apib
  src/03-deals/quotations.apib
  src/changes-backwards-compatible.apib
Labels: Team Marc :de:
