Repository teamleadercrm/api, pull requests merged in 2020-06, with the labels that each got.

#533 [BUG] Fix array of objects
  apiary.apib
  src/02-crm/addresses.apib
  src/02-crm/business-types.apib
Labels: bug

#534 [PRO-3950] Do not require all fields on project.update endpoint
  apiary.apib
  src/07-projects/projects.apib
  src/changes-backwards-compatible.apib
Labels: Team Wombat :koala:

#539 [PRO-4080] Add starts_on field for milestones create and update
  apiary.apib
  src/07-projects/milestones.apib
  src/07-projects/projects.apib
  src/changes-backwards-compatible.apib
Labels: Team Wombat :koala:

#507 IN-2616 Add link type deal to events.list
  apiary.apib
  src/04-calendar/events.apib
  src/changes-backwards-compatible.apib
Labels: Team Pieter :monkey:

#543 In-2616 scheduled filter on tasks list documentation
  apiary.apib
  src/08-tasks/tasks.apib
  src/changes-backwards-compatible.apib
Labels: Team Pieter :monkey:

#544 Expose milestone starts_on on milestones.info/.list
  apiary.apib
  src/07-projects/milestones.apib
  src/changes-backwards-compatible.apib
Labels: Team Wombat :koala:

#542 In-2616 inform the users that they can filter on events list by linked deals
  apiary.apib
  src/04-calendar/events.apib
  src/changes-backwards-compatible.apib
Labels: Team Pieter :monkey:

#540 Set a project's end date
  apiary.apib
  src/07-projects/projects.apib
  src/changes-backwards-compatible.apib
Labels: Team Wombat :koala:
