Repository teamleadercrm/api, pull requests merged in 2021-11, with the labels that each got.

#612 Add `ids` filter to `creditNotes.list` endpoint
  apiary.apib
  src/05-invoicing/credit-notes.apib
  src/changes-backwards-compatible.apib
Labels: Team Tidal :ocean:

#611 Add added_at to products.list
  apiary.apib
  src/06-products/products.apib
Labels: Team Fraf

#613 [CORE-5116] Add added_at to tasks.list endpoint
  apiary.apib
  src/08-tasks/tasks.apib
Labels: Team Fraf

#614 ATL-156: add invoice_id and project_id to /creditNotes.list filters
  apiary.apib
  src/05-invoicing/credit-notes.apib
  src/changes-backwards-compatible.apib
Labels: hold, Team Atlas :earth_africa:
