Repository teamleadercrm/api, pull requests merged in 2021-06, with the labels that each got.

#591 Use new focus domainnames
  README.md
  apiary.apib
  examples/oauth2.php
  src/02-crm/companies.apib
  src/02-crm/contacts.apib
  src/03-deals/deals.apib
  src/05-invoicing/invoices.apib
  src/apiary.apib
  src/authentication.apib
  src/introduction.apib
Labels: hold

#592 Term filter on workTypes.list [TIDAL-236]
  apiary.apib
  src/01-general/work-types.apib
  src/changes-backwards-compatible.apib
Labels: :ocean: Team Tidal

#594 quotations.delete
  apiary.apib
  src/03-deals/quotations.apib
  src/changes-backwards-compatible.apib
Labels: Team Pieter :monkey:
