Repository teamleadercrm/api, pull requests merged in 2022-07, with the labels that each got.

#642 `subscription.info|list` | Fix subscriptions documentation on next renewal date
  apiary.apib
  src/05-invoicing/subscriptions.apib
Labels: bug, Team Atlas :earth_africa:

#644 Documenting subject types for `/files.list`
  apiary.apib
  src/10-files/files.apib
  src/changes-backwards-compatible.apib
Labels: enhancement, Team Atlas :earth_africa:

#646 ATL-1482 Companies.list - Filter on vat_number
  apiary.apib
  src/02-crm/companies.apib
  src/changes-backwards-compatible.apib
Labels: Team Atlas :earth_africa:
