Repository teamleadercrm/api, pull requests merged in 2023-07, with the labels that each got.

#702 ATL-646 Contacts/Companies.list - filter: status
  apiary.apib
  src/02-crm/companies.apib
  src/02-crm/contacts.apib
  src/changes-backwards-compatible.apib
Labels: Team Atlas :earth_africa:

#709 `/invoices.list` | Filter on full `invoice_number`
  apiary.apib
  src/05-invoicing/invoices.apib
  src/changes-backwards-compatible.apib
Labels: enhancement

#711 Add `PriceLists` and extend `Products` endpoints
  apiary.apib
  src/06-products/pricelists.apib
  src/06-products/products.apib
  src/apiary.apib
  src/changes-backwards-compatible.apib
  src/datastructures.apib
Labels: enhancement

#714 Add `currencies.exchangeRates` endpoint
  apiary.apib
  src/01-general/currencies.apib
  src/apiary.apib
  src/changes-backwards-compatible.apib
  src/datastructures.apib
Labels: Team Atlas :earth_africa:

#710 Publish `New Projects` endpoints 🎉
  apiary.apib
  src/07-projects/milestones.apib
  src/07-projects/project-items.apib
  src/07-projects/projects.apib
  src/12-nextgen-projects/materials.apib
  src/12-nextgen-projects/projectGroups.apib
  src/12-nextgen-projects/projectLines.apib
  src/12-nextgen-projects/projects.apib
  src/12-nextgen-projects/tasks.apib
  src/apiary.apib
  src/changes-backwards-compatible.apib
Labels: Team Tidal :ocean:

#719 Add `document_layout` to `subscriptions`
  apiary.apib
  src/05-invoicing/subscriptions.apib
  src/changes-backwards-compatible.apib
Labels: Team Atlas :earth_africa:
