Repository teamleadercrm/api, pull requests merged in 2023-11, with the labels that each got.

#748 New projects: custom fields
  apiary.apib
  src/12-nextgen-projects/projects.apib
  src/changes-backwards-compatible.apib
Labels: Team Tidal :ocean:

#753 Document endpoints as POST method requests
  apiary.apib
  src/06-products/pricelists.apib
  src/06-products/units-of-measure.apib
  src/11-templates/mail-templates.apib
  src/12-nextgen-projects/materials.apib
  src/12-nextgen-projects/tasks.apib
Labels: bug

#755 ATL-2260 Document web hooks for Calls
  apiary.apib
  src/changes-backwards-compatible.apib
  src/datastructures.apib
Labels: Team Atlas :earth_africa:

#754 ATL-2259 Meeting web hooks
  apiary.apib
  src/changes-backwards-compatible.apib
  src/datastructures.apib
Labels: Team Atlas :earth_africa:

#757 Provide meeting recurrence information
  apiary.apib
  src/04-calendar/meetings.apib
  src/changes-backwards-compatible.apib
Labels: Team Atlas :earth_africa:

#758 `/calls.{info,list} | Use completed as the terminology
  apiary.apib
  src/04-calendar/calls.apib
Labels: enhancement

#759 Meetings list: filter by recurrence
  apiary.apib
  src/04-calendar/meetings.apib
  src/changes-backwards-compatible.apib
Labels: Team Atlas :earth_africa:

#740 Calls endpoints
  apiary.apib
  src/04-calendar/call-outcomes.apib
  src/04-calendar/calls.apib
  src/04-calendar/meetings.apib
  src/apiary.apib
  src/changes-backwards-compatible.apib
  src/datastructures.apib
Labels: Team Atlas :earth_africa:

#739 Meetings
  apiary.apib
  src/04-calendar/meetings.apib
  src/changes-backwards-compatible.apib
  src/datastructures.apib
Labels: Team Atlas :earth_africa:

#761 notes.add
  apiary.apib
  src/01-general/notes.apib
  src/changes-backwards-compatible.apib
Labels: Team Atlas :earth_africa:
