Repository teamleadercrm/api, pull requests merged in 2023-12, with the labels that each got.

#760 Notes endpoints
  apiary.apib
  src/01-general/notes.apib
  src/apiary.apib
  src/changes-backwards-compatible.apib
  src/datastructures.apib
Labels: Team Atlas :earth_africa:

#762 Webhooks call.completed and meeting.completed
  apiary.apib
  src/changes-backwards-compatible.apib
  src/datastructures.apib
Labels: Team Atlas :earth_africa:

#772 Document `nextgenProject` subject type for `files` endpoints
  apiary.apib
  src/10-files/files.apib
  src/changes-backwards-compatible.apib
Labels: Team Tidal :ocean:

#774 `/customFieldDefinitions.list` | Document list filters
  apiary.apib
  src/01-general/custom-fields.apib
  src/changes-backwards-compatible.apib
Labels: enhancement

#775 `/emailTracking.create` | Now supports `nextgenProject` Subject Type
  apiary.apib
  src/changes-backwards-compatible.apib
  src/datastructures.apib
Labels: enhancement

#773 Notes.create|Notes.list - Nextgen project subject
  apiary.apib
  src/changes-backwards-compatible.apib
  src/datastructures.apib
Labels: Team Atlas :earth_africa:

#776 Webhook endpoints - nextgen projects
  apiary.apib
  src/changes-backwards-compatible.apib
  src/datastructures.apib
Labels: Team Tidal :ocean:
