Repository teamleadercrm/api, pull requests merged in 2024-09, with the labels that each got.

#849 Add `hourly_rate` to `timeTracking.list` and `timeTracking.info`
  apiary.apib
  src/09-time-tracking/time-tracking.apib
  src/changes-backwards-compatible.apib
Labels: Team Tidal :ocean:, Team Connect🔌

#845 Fetch suppliers in products.info endpoint
  apiary.apib
  src/06-products/products.apib
  src/changes-backwards-compatible.apib
Labels: Team Connect🔌

#850 Add support for currency with exchange rate for deals
  apiary.apib
  src/03-deals/deals.apib
  src/changes-backwards-compatible.apib
Labels: enhancement

#852 Document `will_be_automatically_switched_on` date on `accounts.projects-v2-status`
  apiary.apib
  src/99-other/accounts.apib
  src/changes-backwards-compatible.apib
Labels: Team Tidal :ocean:
