Repository teamleadercrm/api, pull requests merged in 2024-08, with the labels that each got.

#833 Document `/accounts/projects-v2-status`
  apiary.apib
  src/99-other/accounts.apib
  src/apiary.apib
Labels: Team Tidal :ocean:

#834 `legacy_project` optional include in `projects.list` and `projects.info`
  apiary.apib
  src/12-nextgen-projects/projects.apib
  src/changes-backwards-compatible.apib
Labels: Team Tidal :ocean:

#829 CON-408 include a note about uuid migration under API Evolution section
  apiary.apib
  src/roadmap.apib
Labels: Team Connect🔌

#831 custom fields on list endpoints docs
  apiary.apib
  src/02-crm/companies.apib
  src/02-crm/contacts.apib
  src/03-deals/deals.apib
  src/12-nextgen-projects/projects.apib
  src/changes-backwards-compatible.apib
Labels: Team Connect🔌

#832 [CON-427] Tickets.list - document filter.project_ids
  apiary.apib
  src/12-tickets/tickets.apib
  src/changes-backwards-compatible.apib
Labels: Team Connect🔌

#836 fix page format for files.list endpoint
  apiary.apib
  src/10-files/files.apib
Labels: Team Connect🔌

#838 add note about partial update for custom fields
  apiary.apib
  src/introduction.apib
Labels: Team Connect🔌

#840 add reference to tickets.list and tickets.info endpoints
  apiary.apib
  src/12-tickets/tickets.apib
  src/changes-backwards-compatible.apib
Labels: Team Connect🔌

#842 Change 'integer' to 'number'
  apiary.apib
  src/12-tickets/tickets.apib
Labels: bug

#839 Add milestone_id as optional parameter to tickets create and update
  apiary.apib
  src/12-tickets/tickets.apib
  src/changes-backwards-compatible.apib
Labels: Team Connect🔌

#843 Document relates to include for timetracking.list and timetracking.info
  apiary.apib
  src/09-time-tracking/time-tracking.apib
  src/datastructures.apib
Labels: Team Connect🔌

#844 Document `workOrder` on `meetings.info`
  apiary.apib
  src/04-calendar/meetings.apib
  src/changes-backwards-compatible.apib
Labels: Team Tidal :ocean:

#846 [CON-353] Add json content type headers to 201 responses
  apiary.apib
  src/09-time-tracking/time-tracking.apib
  src/09-time-tracking/timers.apib
Labels: Team Connect🔌

#847 `project_id` on `tasks.update`
  apiary.apib
  src/08-tasks/tasks.apib
  src/changes-backwards-compatible.apib
Labels: Team Tidal :ocean:

#848 Document work_type_id for `/meetings.schedule` endpoint
  apiary.apib
  src/04-calendar/meetings.apib
  src/changes-backwards-compatible.apib
Labels: Team Tidal :ocean:
