Repository teamleadercrm/api, pull requests merged in 2024-01, with the labels that each got.

#778 Allow creating task for new project
  apiary.apib
  src/08-tasks/tasks.apib
  src/changes-backwards-compatible.apib
Labels: Team Tidal :ocean:

#777 `/closingDays.list` | Document closing days list endpoint
  apiary.apib
  src/01-general/closing-days.apib
  src/apiary.apib
  src/changes-backwards-compatible.apib
Labels: enhancement

#782 User days off endpoints
  apiary.apib
  src/01-general/day-off-types.apib
  src/01-general/users.apib
  src/apiary.apib
  src/changes-backwards-compatible.apib
Labels: Team Atlas :earth_africa:

#785 Pagination on `projects-v2/tasks.list`
  apiary.apib
  src/12-nextgen-projects/tasks.apib
Labels: Team Tidal :ocean:

#786 Document price budget is now referred to as just budget
  apiary.apib
  src/12-nextgen-projects/materials.apib
  src/12-nextgen-projects/projectGroups.apib
  src/12-nextgen-projects/projects.apib
  src/12-nextgen-projects/tasks.apib
Labels: Team Tidal :ocean:

#787 Expose if the email address of the user is verified or not
  apiary.apib
  src/01-general/users.apib
  src/changes-backwards-compatible.apib
Labels: enhancement

#784 `files.*` | Document ticket subject on endpoints
  apiary.apib
  src/10-files/files.apib
  src/changes-backwards-compatible.apib
Labels: enhancement
